parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\StatsService:
        alias: App\Service\Impl\StatsServiceImpl

    App\Service\LivraisonService:
        alias: App\Service\Impl\LivraisonServiceImpl

    App\Service\ImageStorageService:
        alias: App\Service\Impl\CloudinaryServiceImpl
